#!/bin/sh
set -e

CONFIG=$1
if [ -z "$CONFIG" ]; then
    echo "No config file supplied"
    exit 1
fi
shift


DATA=$1
if [ -z "$DATA" ]; then
    echo "No data directory supplied"
    exit 1
fi
shift

echo 'start-hermes'
echo 'config= '$CONFIG
echo 'data= '$DATA
echo 'current folder= ' $PWD

NEWCONFIG=$DATA/config.toml
echo "hermes src config= "$CONFIG
echo "hermes dst config= "$NEWCONFIG
cp $CONFIG $NEWCONFIG

hermes -c $NEWCONFIG  keys restore chainmain-1 -m "shed crumble dismiss loyal latin million oblige gesture shrug still oxygen custom remove ribbon disorder palace addict again blanket sad flock consider obey popular"  -p "m/44'/394'/0'/0/0"
hermes -c $NEWCONFIG  keys restore cronos_777-1 -m "shed crumble dismiss loyal latin million oblige gesture shrug still oxygen custom remove ribbon disorder palace addict again blanket sad flock consider obey popular"  -p "m/44'/60'/0'/0/0"

hermes  -c $NEWCONFIG keys list chainmain-1
hermes  -c $NEWCONFIG keys list cronos_777-1

hermes -c $NEWCONFIG create channel chainmain-1 cronos_777-1 --port-a transfer --port-b transfer
#chanel, connection already inside genesis
#hermes -c $NEWCONFIG tx raw create-client chainmain-1 cronos_777-1
#hermes -c $NEWCONFIG tx raw create-client cronos_777-1 chainmain-1
hermes -c $NEWCONFIG  start

